spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_practice
    username: root
    password: '{cipher}AQAYBNmxqikr8UJyqmT/DmSKhBICcKpYzohVND7vSjWXLl3PFbVP+M5PYgkzQUM7GJ3akizBRRcovBIZASIjq0cv2tgWl8XviNcWvMLw31Innjxl1wEcm11S4ILG06uNtHoayMgLW+kCQOyaw0lgits0JCKo5OK/TELPbgF+irBZGAKLf7ICB7AwEm0iudZKOOgNusxzrEQ2AR6O5wBkyE5lujK6oA5GkjXQGxPZJElltZHP4pRZIpVbKMJg6To3o2EOEPfHEkf7sUIQWydJ9G9Q2EMt4c+w6depX7rdmUY0qPKB0fcix12dmlRCnyHaNEAuLsusH8ei5T5uazWQv3cFK0dMlOhNZVRmfFFWh2sxNYWgxQqSvFUWHbHvOaAam/o='

token:
  expiration_time: 86400000
  secret: user_token_native

gateway:
  ip: 172.30.19.202

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's order is empty.